#!/usr/bin/env python3
"""
embed_lang.py — 把三个 lang.*.txt 编译成 C# 常量，作为 L10n 的「内联兜底」。

── 为什么要这层兜底 ────────────────────────────────────────────────
L10n 原本只靠 EmbeddedResource + Assembly.GetManifestResourceNames() 发现语言包。
但在 WPF + PublishSingleFile（自包含单文件）发布下，dotnet 把内嵌 .txt 的
「名→数据」映射表弄丢了：exe 里能搜到语言包的纯文本字节，但
GetManifestResourceNames() 返回的清单里没有 WeaselPanel.App.Localization.lang.*.txt，
于是 GetManifestResourceStream 拿到的永远是 null，_packs 为空，T(key) 原样返回键名，
整个界面（含崩溃对话框）变成 "App.Name" / "Nav.Diagnostics" 这种裸键。

本脚本把三个语言包内容直接固化成 C# const string，L10n 加载时若发现某个包
从 EmbeddedResource 没拿到，就用这里的常量补上。常量编译进 IL，永远跟着 exe 走，
不依赖 ResourceManager / 单文件资源解析，从根上消除裸键问题。

用法：
    python3 tools/embed_lang.py
生成：
    src/WeaselPanel.App/Localization/LangResources.g.cs
build.sh 在 publish 之前会调用本脚本，保证常量与 .txt 永远同步。
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACK_DIR = ROOT / "src" / "WeaselPanel.App" / "Localization"
OUT = PACK_DIR / "LangResources.g.cs"

# 语言包文件 → 常量字段名。顺序无关，但保持与 L10n.SupportedLanguages 对齐。
FILES = {
    "lang.zh-Hans.txt": "ZhHans",
    "lang.zh-Hant.txt": "ZhHant",
    "lang.en.txt": "En",
}


def escape_for_raw_string(text: str) -> str:
    """C# 11+ raw string literal：用 \"\"\" 包裹，内容里的 \" 不必转义。
    仅当内容出现连续三个双引号时才需要退化为逐行拼接 —— 语言包不会出现，先校验。"""
    if '"""' in text:
        raise RuntimeError("语言包内容含连续三个双引号，raw string literal 无法安全表达")
    return '"""\n' + text + '\n"""'


def main() -> None:
    blocks = []
    for filename, field in FILES.items():
        path = PACK_DIR / filename
        if not path.is_file():
            raise SystemExit(f"找不到语言包：{path}")
        # 末尾确保有且只有一个换行，避免 raw literal 末行粘连
        content = path.read_text(encoding="utf-8")
        content = content.rstrip("\n") + "\n"
        blocks.append(f"        public const string {field} = {escape_for_raw_string(content)};")

    joined = "\n\n".join(blocks)

    dict_entries = "\n".join(
        f'        ["{code}"] = {field},' for (field, code) in
        [("ZhHans", "zh-Hans"), ("ZhHant", "zh-Hant"), ("En", "en")]
    )

    cs = f"""// <auto-generated>
// 本文件由 tools/embed_lang.py 从 Localization/lang.*.txt 生成，请勿手工编辑。
// 改文案请改 .txt，然后重跑本脚本（build.sh 会自动跑）。
// 作用：L10n 在 PublishSingleFile 下拿不到 EmbeddedResource 名时的内联兜底，
//       保证语言包永远随 exe 走，界面不会出现裸键名。
// </auto-generated>

namespace WeaselPanel.App.Localization;

internal static class LangResources
{{
{joined}

    /// <summary>code → 整包文本。L10n 加载时逐个比对：EmbeddedResource 没拿到的就用这里补。</summary>
    public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> AllPacks =
        new System.Collections.Generic.Dictionary<string, string>
        {{
{dict_entries}
        }};
}}
"""

    OUT.write_text(cs, encoding="utf-8")
    total = sum(len((PACK_DIR / f).read_text(encoding="utf-8").splitlines()) for f in FILES)
    print(f"✅ 生成 {OUT.name}（{len(FILES)} 个语言包，约 {total} 键）")


if __name__ == "__main__":
    main()
